keys:
  users:
    - &rap_zion age1y8vwxjyzhftr8n0mry5zkq34ra5g69z927p9s3qrj04gzqwasc8q3fqlgf
creation_rules:
  - path_regex: hosts/zion/secrets.yaml$
    key_groups:
      - age:
          - *rap_zion
