{
  pkgs,
  lib,
  self,
  config,
  ...
}:
{
  services.kanshi =
    let
      hyprlandCfg = config.roles.desktop.hyprland;
      hyprctl =
        if hyprlandCfg.enable && hyprlandCfg.configOnly then
          "/usr/bin/hyprctl"
        else
          lib.getExe' pkgs.hyprland "hyprctl";
      workspaceSetup =
        let
          wallpaperPath = "${self.outPath}/extra/wallpapers";
          wallpapers = builtins.attrNames (builtins.readDir wallpaperPath);
        in
        pkgs.writeShellScriptBin "workspaceSetup" ''
          set -euo pipefail

          primary="''${1:?missing primary monitor}"
          secondary="''${2:?missing secondary monitor}"

          # Generate workspace config
          cat > "$HOME/.config/hypr/workspaces.conf" <<EOF
          # Generated by kanshi on $(date +"%d-%m-%Y at %H:%M:%S"). Do not edit manually.

          workspace = 1, monitor:$primary, default:true
          workspace = 2, monitor:$primary
          workspace = 3, monitor:$secondary, default:true
          workspace = 4, monitor:$secondary
          EOF

          ${hyprctl} reload
          ${hyprctl} dispatch moveworkspacetomonitor "1 $primary"
          ${hyprctl} dispatch moveworkspacetomonitor "2 $primary"
          ${hyprctl} dispatch moveworkspacetomonitor "3 $secondary"
          ${hyprctl} dispatch moveworkspacetomonitor "4 $secondary"

          # Set random wallpaper
          wall_one=$(shuf -n 1 -e ${toString wallpapers})
          wall_two=$(shuf -n 1 -e ${toString wallpapers})
          ${hyprctl} hyprpaper wallpaper "$primary, ${wallpaperPath}/$wall_one"
          ${hyprctl} hyprpaper wallpaper "$secondary, ${wallpaperPath}/$wall_two"

          ${hyprctl} dispatch focusmonitor "$primary"
          ${hyprctl} dispatch workspace 1
          systemctl --user restart waybar.service
        '';

      # toMonitorId turns a kanshi criteria string into the identifier Hyprland's
      # workspace/dispatch syntax expects: connector names (DP-1, eDP-1, ...) are
      # passed through as-is, descriptions (which always contain spaces) are
      # prefixed with "desc:".
      toMonitorId = criteria: if lib.hasInfix " " criteria then "desc:${criteria}" else criteria;

      # mkExec picks which output(s) receive workspaces. A single entry means
      # all four workspaces go to that one monitor (primary == secondary).
      mkExec =
        workspaceOutputs:
        let
          primary = toMonitorId (builtins.elemAt workspaceOutputs 0);
          secondary = toMonitorId (
            builtins.elemAt workspaceOutputs (if builtins.length workspaceOutputs == 2 then 1 else 0)
          );
        in
        "${lib.getExe workspaceSetup} ${
          lib.escapeShellArgs [
            primary
            secondary
          ]
        }";

      mkProfile =
        {
          name,
          outputs,
          workspaceOutputs,
        }:
        {
          profile = {
            inherit name outputs;
            exec = mkExec workspaceOutputs;
          };
        };
    in
    {
      enable = true;
      systemdTarget = "hyprland-session.target";

      settings = [
        {
          output = {
            criteria = "eDP-1";
            position = "6000,0";
            mode = "1920x1200@60.00Hz";
          };
        }

        {
          # Default profile, without exec
          profile = {
            name = "undocked";
            outputs = [
              {
                criteria = "eDP-1";
              }
            ];
          };
        }

        (mkProfile {
          name = "office";
          outputs = [
            {
              # TODO: test this connector, may overload this config with all possible connectors
              criteria = "DP-1";
              mode = "3440x1440@99.98Hz";
              scale = 1.0;
            }
            {
              criteria = "eDP-1";
            }
          ];
          workspaceOutputs = [ "DP-1" ];
        })

        # TODO: Add meeting room here

        (mkProfile {
          name = "home-firefly";
          outputs = [
            {
              criteria = "Dell Inc. AW2725Q G2QC174";
              scale = 1.5;
              position = "2560,0";
              mode = "3840x2160@239.99Hz";
            }
            {
              criteria = "Samsung Electric Company LC27G7xT H4ZNC00167";
              scale = 1.0;
              position = "0,0";
              mode = "2560x1440@239.96Hz";
            }
            {
              criteria = "eDP-1";
            }
          ];
          workspaceOutputs = [
            "Dell Inc. AW2725Q G2QC174"
            "Samsung Electric Company LC27G7xT H4ZNC00167"
          ];
        })

        (mkProfile {
          name = "home";
          outputs = [
            {
              criteria = "Dell Inc. AW2725Q G2QC174";
              scale = 1.5;
              position = "2560,0";
              mode = "3840x2160@239.99Hz";
            }
            {
              criteria = "Samsung Electric Company LC27G7xT H4ZNC00167";
              scale = 1.0;
              position = "0,0";
              mode = "2560x1440@239.96Hz";
            }
          ];
          workspaceOutputs = [
            "Dell Inc. AW2725Q G2QC174"
            "Samsung Electric Company LC27G7xT H4ZNC00167"
          ];
        })
      ];
    };
}
