{ pkgs, lib, ... }:
{
  services.kanshi =
    let
      workspaceSetup = pkgs.writeShellScriptBin "workspaceSetup" ''
        primary="$1"
        secondary="$2"

        cat <<EOF > "$HOME/.config/hypr/workspaces.conf"
        # Generated by RAPSN workspaceSetup on "$(date +"%d-%m-%Y at %H:%M:%S")".

        workspace=1,monitor:$primary,default:true
        workspace=2,monitor:$primary
        workspace=3,monitor:$primary
        workspace=4,monitor:$secondary,default:true
        workspace=5,monitor:$secondary
        workspace=6,monitor:$secondary
        EOF

        ${lib.getExe' pkgs.hyprland "hyprctl"} dispatch workspace 1
      '';
    in
    {
      enable = true;
      systemdTarget = "hyprland-session.target";

      settings = [
        # ----- FIREFLY ----- #
        {
          profile = {
            name = "firefly-undocked";
            outputs = [
              {
                criteria = "eDP-1";
                scale = 1.0;
                status = "enable";
              }
            ];
          };
        }

        {
          profile = {
            name = "firefly-home";
            outputs = [
              {
                criteria = "DP-1";
                position = "2560,0";
                mode = "3840x2160@143.99Hz";
              }
              {
                criteria = "HDMI-A-1";
                scale = 1.0;
                position = "0,0";
                mode = "2560x1440@144.00Hz";
              }
              {
                criteria = "eDP-1";
                status = "disable";
              }
            ];
            exec = "${lib.getExe workspaceSetup} DP-1 HDMI-A-1";
          };
        }

        {
          profile = {
            name = "firefly-office";
            outputs = [
              {
                criteria = "DP-8";
                position = "0,0";
              }
              {
                criteria = "DP-9";
                position = "1920,0";
              }
              {
                criteria = "eDP-1";
                status = "disable";
              }
            ];
            exec = "${lib.getExe workspaceSetup} DP-8 DP-9";
          };
        }

        # ----- ZION ----- #
        {
          profile = {
            name = "zion-home";
            outputs = [
              {
                criteria = "DP-1";
                scale = 1.5;
                position = "2560,0";
                mode = "3840x2160@239.99Hz";
              }
              {
                criteria = "DP-2";
                scale = 1.0;
                position = "0,0";
                mode = "2560x1440@144.00Hz";
              }
            ];
            exec = "${lib.getExe workspaceSetup} DP-1 DP-2";
          };
        }
      ];
    };
}
