{
  pkgs,
  lib,
  self,
  config,
  ...
}:
{
  services.kanshi =
    let
      hyprlandCfg = config.roles.desktop.hyprland;
      hyprctl =
        if hyprlandCfg.enable && hyprlandCfg.configOnly then
          "/usr/bin/hyprctl"
        else
          lib.getExe' pkgs.hyprland "hyprctl";
      workspaceSetup =
        let
          wallpaperPath = "${self.outPath}/extra/wallpapers";
          wallpapers = builtins.attrNames (builtins.readDir wallpaperPath);
        in
        pkgs.writeShellScriptBin "workspaceSetup" ''
          set -euo pipefail

          primary_desc="''${1:?missing primary monitor description}"
          secondary_desc="''${2:-""}"
          monitors="$(${hyprctl} monitors -j)"

          # get_output gets the output name of a monitor description.
          get_output() {
            ${lib.getExe pkgs.jq} -r --arg matcher "$1" '
              [.[] | select(.description | test($matcher)) | .name][0]' <<< "$monitors"
          }

          primary="$(get_output $primary_desc)"
          secondary="$(get_output $secondary_desc)"

          # Generate workspace config
          cat > "$HOME/.config/hypr/workspaces.conf" <<EOF
          # Generated by kanshi on $(date +"%d-%m-%Y at %H:%M:%S"). Do not edit manually.

          workspace = 1, monitor:$primary, default:true
          workspace = 2, monitor:$primary
          workspace = 3, monitor:$secondary, default:true
          workspace = 4, monitor:$secondary
          EOF

          ${hyprctl} reload
          ${hyprctl} dispatch moveworkspacetomonitor "1 $primary"
          ${hyprctl} dispatch moveworkspacetomonitor "2 $primary"
          ${hyprctl} dispatch moveworkspacetomonitor "3 $secondary"
          ${hyprctl} dispatch moveworkspacetomonitor "4 $secondary"

          # Set random wallpaper

          wall_one=$(shuf -n 1 -e ${toString wallpapers})
          wall_two=$(shuf -n 1 -e ${toString wallpapers})
          ${hyprctl} hyprpaper wallpaper "$primary, ${wallpaperPath}/$(shuf -n 1 -e ${toString wallpapers})"
          ${hyprctl} hyprpaper wallpaper "$secondary, ${wallpaperPath}/$(shuf -n 1 -e ${toString wallpapers})"

          ${hyprctl} dispatch focusmonitor "$primary"
          ${hyprctl} dispatch workspace 1
          systemctl --user restart waybar.service
        '';

      # mkExec collects all outputs and creates args out of it, the workspaceSetup script only takes the first two.
      mkExec =
        outputs:
        "${lib.getExe workspaceSetup} ${lib.escapeShellArgs (map (output: output.criteria) outputs)}";

      mkProfile =
        { name, outputs }:
        {
          profile = {
            inherit name outputs;
            exec = mkExec outputs;
          };
        };
    in
    {
      enable = true;
      systemdTarget = "hyprland-session.target";

      settings = [
        {
          output = {
            criteria = "eDP-1";
            position = "0,0";
            mode = "1920x1200@60.00Hz";
          };
        }

        {
          # Default profile, without exec
          profile = {
            name = "undocked";
            outputs = [
              {
                criteria = "eDP-1";
              }
            ];
          };
        }

        (mkProfile {
          name = "office";
          outputs = [
            {
              criteria = "HP Inc. HP 534pm *";
              mode = "3440x1440@99.98Hz";
              scale = 1.0;
            }
            {
              criteria = "*";
            }
          ];
        })

        # TODO: Add meeting room here

        (mkProfile {
          name = "home-firefly";
          outputs = [
            {
              criteria = "Dell Inc. AW2725Q G2QC174";
              scale = 1.5;
              position = "2560,0";
              mode = "3840x2160@239.99Hz";
            }
            {
              criteria = "Samsung Electric Company LC27G7xT H4ZNC00167";
              scale = 1.0;
              position = "0,0";
              mode = "2560x1440@239.96Hz";
            }
            {
              criteria = "eDP-1";
              status = "disable";
            }
          ];
        })

        (mkProfile {
          name = "home";
          outputs = [
            {
              criteria = "Dell Inc. AW2725Q G2QC174";
              scale = 1.5;
              position = "2560,0";
              mode = "3840x2160@239.99Hz";
            }
            {
              criteria = "Samsung Electric Company LC27G7xT H4ZNC00167";
              scale = 1.0;
              position = "0,0";
              mode = "2560x1440@239.96Hz";
            }
          ];
        })
      ];
    };
}
