{
  pkgs,
  lib,
  mylib,
  config,
  ...
}:
let
  cfg = config.roles.desktop.hyprland;
in
{
  options.roles.desktop.hyprland = {
    enable = lib.mkEnableOption "Enable hyprland";

    package = lib.mkPackageOption pkgs "hyprland" {
      nullable = true;
    };

    autostart = mylib.mkOpt (lib.types.listOf lib.types.str) "autostart";

    hyprlock = {
      enable = lib.mkEnableOption "Enable hyprlock";
    };

    hypridle = {
      enable = lib.mkEnableOption "Enable hypridle";
      cmd = mylib.mkOpt lib.types.str "Path to binary";
    };
  };

  imports = [
    ./addons/hypridle.nix
    ./addons/hyprlock.nix

    ./keybinds.nix
  ];

  config = lib.mkIf cfg.enable {

    home.packages = builtins.attrValues {
      inherit (pkgs) hyprland-qtutils rofimoji slurp;
    };

    # environment.d defines environment variables for the user session, beyond shell level.
    # It is processed by `systemd --user`, basically after login.
    xdg.configFile."environment.d/envvars.conf".text = ''
      PATH="$HOME/.nix-profile/bin:$PATH"
    '';

    # TODO: remove this when changed to lua
    services.hyprpaper.enable = true;

    catppuccin.hyprland.enable = false;
    catppuccin.hyprlock.enable = false;
    wayland.windowManager.hyprland = {
      enable = true;
      configType = "hyprlang";
      inherit (cfg) package;
      systemd.enable = true;

      settings = {
        general = {
          gaps_in = 8;
          gaps_out = 10;
          border_size = 3;
        };

        # Source autogenerated configs
        source = [
          "${config.xdg.configHome}/hypr/monitors.conf"
          "${config.xdg.configHome}/hypr/workspaces.conf"
        ];

        # Auto tile new windows
        dwindle = {
          preserve_split = "yes";
          special_scale_factor = 0.8;
        };

        input = {
          kb_layout = "eu,de,de";
          kb_variant = ",neo_qwertz,";
          repeat_rate = 45;
          repeat_delay = 150;
          accel_profile = "flat";
          sensitivity = 1; # -1.0 - 1.0, 0 means no modification.
        };

        xwayland = {
          force_zero_scaling = true;
        };

        decoration = {
          blur = {
            enabled = true;
            size = 3;
            passes = 2;
            ignore_opacity = true;
            new_optimizations = true;
          };
          rounding = 5;
        };

        # Autostart
        exec-once = [
          "[ workspace special:scratchy silent ] alacritty -t scratchy"

          "[ workspace special:aux silent ] sleep 2 && chromium --profile-directory=Default --app-id=dlgohinmglaoopaiplliaecdpmnepmga"
        ]
        ++ cfg.autostart;

        windowrule = [
          "match:class ^(firefox)$, workspace 3"
          "match:class ^(chromium-browser)$, workspace 4"

          "match:class ^(.*mumble.*)$, workspace special:aux silent"
          "match:class ^(.*keepassxc.*)$, workspace special:aux silent"

          # Force floating
          "match:class steam, float yes"
          "match:class ^(.*nextcloud.*)$, float yes"
        ];

      };
    };

  };
}
