name: Nix
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
permissions:
  contents: read
jobs:
  flake-check:
    name: Flake check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true
      - name: Cache Nix store
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check flake
        run: nix flake check --print-build-logs
  hosts:
    name: Host ${{ matrix.host }}
    runs-on: ${{ matrix.runner }}
    needs: flake-check
    strategy:
      fail-fast: false
      matrix:
        include:
          - host: zion
            runner: ubuntu-latest
            command: nix build .#nixosConfigurations.zion.config.system.build.toplevel --print-build-logs
          - host: kubex
            runner: ubuntu-latest
            command: nix build .#nixosConfigurations.kubex.config.system.build.toplevel --print-build-logs
          - host: vinox
            runner: ubuntu-latest
            command: nix build .#nixosConfigurations.vinox.config.system.build.toplevel --print-build-logs
            # - host: nixberry
            #   runner: ubuntu-24.04-arm
            #   command: nix build .#nixosConfigurations.nixberry.config.system.build.toplevel --print-build-logs
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true
      - name: Cache Nix store
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Test host
        run: ${{ matrix.command }}
